"""New: Datetime now func on dba active 

Revision ID: 05cfc7b537b0
Revises: 5b82adced494
Create Date: 2024-05-19 09:14:32.478686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05cfc7b537b0'
down_revision: Union[str, None] = '5b82adced494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
