"""Descrição das Alterações

Revision ID: 5b82adced494
Revises: f63481284c15
Create Date: 2024-05-19 09:06:44.411504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b82adced494'
down_revision: Union[str, None] = 'f63481284c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallpaper', sa.Column('download_count', sa.Integer(), nullable=True))
    op.add_column('wallpaper', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallpaper', 'like_count')
    op.drop_column('wallpaper', 'download_count')
    # ### end Alembic commands ###
