"""Initial migration

Revision ID: f63481284c15
Revises: 
Create Date: 2024-05-13 20:49:25.936624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63481284c15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('wallpaper',
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('upload_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('wallpaper_id')
    )
    op.create_table('download',
    sa.Column('download_id', sa.Integer(), nullable=False),
    sa.Column('wallpaper_id', sa.Integer(), nullable=True),
    sa.Column('download_datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpaper.wallpaper_id'], ),
    sa.PrimaryKeyConstraint('download_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download')
    op.drop_table('wallpaper')
    op.drop_table('category')
    # ### end Alembic commands ###
